---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8080}]
        - ["private_network", {ip: "192.168.33.33"}]
  # - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[wordpress::test-user]
      - recipe[wordpress]
    attributes:
      mysql:
        server_root_password: p@ass0wrd
        server_repl_password: p@ass0wrd
        server_debian_password: p@ass0wrd
      wordpress:
        owner: wordpress
        group: wordpress
        sites:
          - name: wp1.example.com
            version: '3.4.1'
            lang: ja
            db:
              name: wp1
              user: wordpress1
              pass: wordpress1
          - name: wp2.example.com
            version: '4.0'
            lang: ja
            db:
              name: wp2
              user: wordpress2
              pass: wordpress2
